# Generated by Django 5.2.7 on 2025-11-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Детальний опис')),
                ('type', models.CharField(blank=True, choices=[('foot', 'Пішохідна'), ('bus_1', 'Автобусна (1 день)'), ('bus_2', 'Автобусна (2 дні)')], default='foot', max_length=200, null=True, verbose_name='Тип екскурсії')),
                ('keyword', models.CharField(max_length=200)),
                ('is_lunch_included', models.BooleanField(default=False, verbose_name='Обід включено')),
                ('price', models.DecimalField(decimal_places=2, max_digits=100, verbose_name='Ціна')),
                ('conditions', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Умови і оплата')),
                ('vidguki', models.TextField(blank=True, max_length=20000, null=True, verbose_name='Відгуки')),
            ],
        ),
    ]
