# Generated by Django 5.2.7 on 2025-10-20 11:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_post_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='note',
            old_name='content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='reminder'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.category'),
        ),
    ]
