# Generated by Django 5.2.7 on 2025-10-26 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_note_category_alter_note_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category_name',
        ),
    ]
