# Generated by Django 5.2.7 on 2025-10-17 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='cat_title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='category',
            new_name='note_category',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='created_at',
            new_name='note_created_at',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='reminder',
            new_name='note_reminder',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='text',
            new_name='note_text',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='title',
            new_name='note_title',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='updated_at',
            new_name='note_updated_at',
        ),
    ]
